InsuranceWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsuranceWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

InsuranceWebApplication/Controllers/InsuranceClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InsuranceWebApplication.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace InsuranceWebApplication.Controllers
{
    public class InsuranceClaimController : Controller
    {
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        // GET: InsuranceClaim
        public ActionResult Index()
        {
            return View();
        }

        // GET: InsuranceClaim/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Agent,Manager")]
        public ActionResult List()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var claims = db.InsuranceClaims.ToList();
            return View(claims);
        }

        // GET: InsuranceClaim/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InsuranceClaim/Create
        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult Create(InsuranceClaimViewModel model)
        {
            try
            {
                using (var db = new ApplicationDbContext())
                {
                    db.InsuranceClaims.Add(new InsuranceClaim
                    {
                        Description = model.Description,
                        UserId = User.Identity.GetUserId(),
                        EvaluateClaim = false
                    });

                    db.SaveChanges();
                }
                
                return RedirectToAction("InsuranceClaims", "Me");
            }
            catch
            {
                return View();
            }
        }

        // GET: InsuranceClaim/Edit/5
        public ActionResult Edit(int? id)
        {
            using (var db = new ApplicationDbContext())
            {
                var claim = db.InsuranceClaims.Find(id);
                if (claim == null)
                {
                    return HttpNotFound();
                }

                var claimViewModel = new InsuranceClaimViewModel(claim);

                var agentRole = db.Roles.First(role => role.Name.Equals("Agent"));
                claimViewModel.Agents =
                    db.Users.Where(user => user.Roles.Any(role => role.RoleId.Equals(agentRole.Id))).ToList();

                return View(claimViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, InsuranceClaimViewModel claim)
        {
            if (ModelState.IsValid)
            {
                ApplicationDbContext db = new ApplicationDbContext();


                var Model = db.InsuranceClaims.Find(id);
                Model.Description = claim.Description;
                Model.EvaluateClaim = claim.EvaluateClaim;
                Model.AgentId = claim.AgentId;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(claim);
        }

        // POST: InsuranceClaim/Edit/5


        // GET: InsuranceClaim/Delete/5
        public ActionResult Delete(int id)
        {
            ApplicationDbContext db = new ApplicationDbContext();


            var claim = db.InsuranceClaims.Find(id);
            return View(claim);
            
        }

        // POST: InsuranceClaim/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, InsuranceClaim claim)
        {
            if (ModelState.IsValid)
            {
                using (ApplicationDbContext db = new ApplicationDbContext())
                {


                    var Claim = db.InsuranceClaims.Find(id);
                    db.InsuranceClaims.Remove(Claim);                    
                    db.SaveChanges();


                    return RedirectToAction("List");
                }
            }
            return RedirectToAction("Index");
        }
    }
}

InsuranceWebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InsuranceWebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

InsuranceWebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Insurance Application</h1>
    <p class="lead">Submit your insurance claims for further assistance.</p>
    <p><a href="@Url.Action("Create", "InsuranceClaim")" class="btn btn-primary btn-lg">Submit your claim &raquo;</a></p>
</div>

@if (User.IsInRole("Manager"))
{
    <div class="row">
        <div class="col-md-4">
            <h2>Insurance Claims</h2>
            <p>See and manage all insurance claims.</p>
            <p><a class="btn btn-default" href="@Url.Action("List", "InsuranceClaim")">View All Insurance Claims &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Customers</h2>
            <p>See and manage all insurance claims.</p>
            <p><a class="btn btn-default" href="@Url.Action("Index", "Customer")">View All Customers &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Agents</h2>
            <p>See and manage all agents.</p>
            <p><a class="btn btn-default" href="@Url.Action("create", "Agent")">Create Agent &raquo;</a></p>
        </div>
    </div>
}